title: "PaperSpan Help"
description: "Help Center for PaperSpan"
remote_theme: pmarsceill/just-the-docs
markdown: kramdown
plugins:
  - jekyll-include-cache
# Enable search
search_enabled: true
footer_content: ""
# Site URL
url: "https://paperspan.github.io/help.paperspan.com"
# logo: /logo.png
nav_external_links:
  - title: "PaperSpan.com"
    url: "https://paperspan.com"
    open_in_new_tab: true
# Navigation (only include files that exist!)
nav:
  - Apps: index.md
  - Saving Articles:
      - From Android: saving/android.md
      - From iOS: saving/ios.md
      - From Desktop: saving/web.md
      - From Browser Extensions: saving/browser.md
  - Organizing: organizing.md
  - Text to Speech: texttospeech.md
  - Highlights: highlights.md
  - Kindle: kindle.md
  - Notes: notes.md
  - Reading Statistics: stats.md
  - Offline Reading: offline.md
  - Import & Export: import-export.md
