title: "PaperSpan Help"
description: "Help Center for PaperSpan"
remote_theme: pmarsceill/just-the-docs
# Enable search
search_enabled: true

# Site URL
url: "https://paperspan.github.io/help.paperspan.com"
# logo: /logo.png

# Navigation (only include files that exist!)
nav:
  - Apps: index.md
  - Saving Articles:
      - From Android: saving/android.md
      - From iOS: saving/ios.md
      - From Desktop: saving/web.md
      - From Browser Extensions: saving/browser.md
  - Organizing: organizing.md
  - Text to Speech: texttospeech.md
  - Highlights: highlights.md
  - Kindle: kindle.md
  - Notes: notes.md
  - Reading Statistics: stats.md
  - Offline Reading: offline.md
  - Import & Export: import-export.md
